[package]
name = "eth_wallet_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.13"
tokio = { version = "1.36", features = ["full"] }
num_cpus = "1.16.0"
futures = "0.3.30"

